spring:
  application:
    name: synergyproject
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/news
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_loading_no_trans: true
    hibernate:
      ddl-auto: validate